version: '3.1'

services:
  jupyter:
    build: './jupyter'
    restart: always
    ports:
      - 8888:8888
    environment:
      JUPYTER_ENABLE_LAB: 'yes'
    volumes:
      - ./jupyter/notebooks:/home/jovyan/work
  neo4j:
    image: 'neo4j:5.6.0'
    restart: always
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - /home/xsvafr/neo4j/data:/data

